### PR TITLE
ByteUnits: fix TB being represented as PB

### PR DESCRIPTION
**Pull request by domenkozar**
cc @chrissound

### CODE REVIEW

**Comment by chrissound** [comment]
Thanks :+1:

**Comment by domenkozar** [comment]
I'd appreciate a release :)

**Comment by chrissound** [comment]
Should be done now + on hackage https://github.com/chrissound/byteunits/commit/72499a629da7771118ad36eed53d3c7209133676

**Comment by domenkozar** [comment]
Thanks!

**Pull request merged**
